services:
  db:
    image: timescale/timescaledb:latest-pg14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: iot_dashboard
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - timescale_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d iot_dashboard"]
      interval: 5s
      timeout: 5s
      retries: 5

  broker:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

  backend:
    build:
      context: ./backend
    environment:
      - DATABASE_URL=postgresql://postgres:rootpassword@db:5432/iot_dashboard
      - SECRET_KEY=minha_chave_super_secreta_jwt
      - MQTT_BROKER_URL=broker
    depends_on:
      db:
        condition: service_healthy
      broker:
        condition: service_started

  frontend:
    build:
      context: ./frontend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080/api
      - NEXT_PUBLIC_WS_URL=ws://localhost:8080/ws/stream
    depends_on:
      - backend

  proxy:
    build:
      context: ./proxy
    ports:
      - "8080:80"
    depends_on:
      - frontend
      - backend

  edge:
    build:
      context: ./edge
    environment:
      - MQTT_BROKER_URL=broker
    depends_on:
      - broker

volumes:
  timescale_data:
